language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: fcd6d8c28da900609a2cf903716d858621b8ce68152edbcebe6908a9a3f5d3d5
before_install:
  - gem update --system
  - gem update bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp spec/support/database.yml.travis spec/support/database.yml
